name: travel_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
# UI packages
  core:
    path: packages/core  
  easy_localization: ^3.0.5
# router
  auto_route: ^8.0.2
#Service Locator
  get_it: ^7.6.8
  injectable: ^2.4.1  
#responsive
  flutter_screenutil: ^5.9.0
  animated_bottom_navigation_bar: ^1.3.3
  carousel_slider: ^5.0.0  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  import_sorter: ^4.6.0
  flutter_gen_runner: ^5.3.2
  auto_route_generator: ^8.0.0
  injectable_generator: ^2.4.1
  build_runner: ^2.4.9
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
